### ISSUE TITLE
attempt to call a nil value (field 'open')

### ISSUE THREAD

**Issue by Mte90** [editorconfig/editorconfig-textadept#1]
`...pt_9.5.x86_64/modules/textadept/editing/editorconfig.lua:95: attempt to call a nil value (field 'open')`

I get that error in a new tab so I am not sure that editorconfig is working.

**Comment by Mte90** [comment]
Seems that the problem is that this code is using editorconfig lua core .0.2.0 but released there is only the 0.1.1 so using a previous code like that I don't get any error https://github.com/editorconfig/editorconfig-textadept/blob/118e60063aa8962e7ceb689fcd9a3b6ca4b903cc/editorconfig.lua

**Comment by randstr** [comment]
I will have a look, thanks.

**Comment by randstr** [comment]
I created a release for editorconfig-core-lua 0.2.0. Leaving this open to consider adding a version check to editorconfig.lua.
